export {default as Logo} from './Logo';
export {default as Menu} from './Menu';
export {default as Header} from './Header';
export {default as Icon} from './Icon';
export {default as Layout} from './Layout';
export {default as Main} from './Main';
export {default as Footer} from './Footer';
export {default as CurrentExhibition} from './CurrentExhibition';
export {default as Artist} from './Artist';
