on: 
  push:
    branches:
      - master
name: Publish Wordpress Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: s185472.gridserver.com
        username: new-danielfariagallery.com
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: domains/api.danielfariagallery.com/html/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
          - wp-content/uploads/**/
          - wp-content/uploads/**/*
          - wp-content/plugins/**/
          - wp-content/plugins/**/*
